import React from 'react';
import Head from 'next/head';
import Link from 'next/link';

const Layout = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='flex min-h-screen flex-col justify-between'>
        <header>
        <nav className='flex h-12 items-center p-4 justify-between shadow-md'>
            <Link href="/" className='font-bold'>
                E-shop
            </Link>
            <div>
                <Link className='text-lg p-2 mr-2' href="/">Cart</Link>
                <Link className='text-lg p-2' href="/">Login</Link>
            </div>
        </nav>
            
        </header>
        <main className='container px-4'>Main</main>

        <footer className='flex h-10 items-center justify-center shadow-inner'>Footer</footer>
      </div>
    </>
  );
};

export default Layout;
